[package]
description = "suisei-music companion"
edition = "2018"
homepage = "https://github.com/outloudvi/suimu"
license = "MIT"
name = "suimu"
repository = "https://github.com/outloudvi/suimu"
version = "0.1.0"

[dependencies]
clap = "~3.0.0-beta.2"
csv = "1.1.6"
log = "0.4.14"
pretty_env_logger = "0.4.0"
serde = {version = "1.0.126", features = ["derive"]}

[[bin]]
name = "suimu-check"
path = "src/bin/suimu-check.rs"
