name: Audit
on:
  push:
    branches:
      - gui
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
jobs:
  tauri_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cd src-tauri
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
