name: Cargo check
on:
  - push
  - pull_request
jobs:
  cargo_check:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check