on: push
name: Format
jobs:
  tauri_clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  web_format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: |
          cd src-web
          npm install
          npm run format:check
